import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { getReport, processData, getRawData } from '../api';
import { downloadPropertiesPdf } from '../pdfExport';
import './Dashboard.css';

function DimCard({ name, score }) {
  const status = score >= 90 ? 'PASS' : score >= 70 ? 'WARN' : 'FAIL';
  const reasoning =
    status === 'PASS'
      ? 'High reliability.'
      : status === 'WARN'
        ? 'Needs attention.'
        : 'Critical issues found.';

  return (
    <div className="dim-card" id={`dim-${name.toLowerCase()}`}>
      <h3>{name}</h3>
      <p>Score: <strong>{score}%</strong></p>
      <p>Status: <span className={`status-${status}`}>{status}</span></p>
      <p><small>{reasoning}</small></p>
    </div>
  );
}

export default function Dashboard() {
  const [report, setReport] = useState(null);
  const [rawData, setRawData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [processing, setProcessing] = useState(false);
  const [error, setError] = useState(null);

  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');

  const loadReport = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await getReport();
      if (data.error) throw new Error(data.error);
      setReport(data);
    } catch (e) {
      setError(e.message);
      setReport(null);
    } finally {
      setLoading(false);
    }
  };

  const loadRawData = async () => {
    try {
      const list = await getRawData();
      setRawData(Array.isArray(list) ? list : []);
    } catch {
      setRawData([]);
    }
  };

  useEffect(() => {
    loadReport();
    loadRawData();
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!startDate || !endDate) return;
    setProcessing(true);
    setError(null);
    try {
      const data = await processData(startDate, endDate);
      setReport(data.report);
      const list = data.raw_data?.properties;
      setRawData(Array.isArray(list) ? list : []);
    } catch (e) {
      setError(e.message);
    } finally {
      setProcessing(false);
    }
  };

  const handleDownloadPdf = () => {
    downloadPropertiesPdf(rawData);
  };

  return (
    <div className="dashboard">
      <header className="dashboard-header">
        <h1>Data Trustability Dashboard</h1>
        <p>Generated by Gesix Data Quality Framework</p>
        <nav>
          <Link to="/">Home</Link>
        </nav>
      </header>

      <section className="control-panel">
        <h3>Run New Analysis</h3>
        <form onSubmit={handleSubmit} className="dashboard-form">
          <div className="form-group">
            <label htmlFor="start_date">Start Date</label>
            <input
              type="date"
              id="start_date"
              name="start_date"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              required
              disabled={processing}
            />
          </div>
          <div className="form-group">
            <label htmlFor="end_date">End Date</label>
            <input
              type="date"
              id="end_date"
              name="end_date"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              required
              disabled={processing}
            />
          </div>
          <button type="submit" className="btn-process" disabled={processing}>
            {processing ? 'Processing... Please wait' : 'Process Data'}
          </button>
        </form>
      </section>

      {error && (
        <div className="dashboard-error">
          {error}
        </div>
      )}

      {loading && !report && !error && (
        <p className="dashboard-loading">Loading report...</p>
      )}

      {report && !report.error && report.status !== 'No Data Found for this period' && (
        <>
          <section className="score-box">
            <h2>Overall Trustability: <span id="overall-score">{report.overall_trustability}%</span></h2>
            <p>Total Records Processed: <span id="total-count">{report.total_records}</span></p>
          </section>

          <section className="dimensions-grid">
            {report.dimensions &&
              Object.entries(report.dimensions).map(([name, score]) => (
                <DimCard key={name} name={name} score={score} />
              ))}
          </section>
        </>
      )}

      {report && report.status === 'No Data Found for this period' && (
        <section className="score-box no-data">
          <h2>No data found</h2>
          <p>Run an analysis with a different date range.</p>
        </section>
      )}

      <section className="generated-data-section">
        <h3>Generated data (API properties)</h3>
        <p className="generated-data-hint">Data produced when you click Process. Download as PDF below.</p>
        {rawData.length > 0 ? (
          <>
            <div className="table-wrap">
              <table className="generated-data-table">
                <thead>
                  <tr>
                    <th>Address</th>
                    <th>Price</th>
                    <th>Listed date</th>
                  </tr>
                </thead>
                <tbody>
                  {rawData.map((row, i) => (
                    <tr key={i}>
                      <td>{row.add ?? row.address ?? '—'}</td>
                      <td>{row.price != null ? row.price : '—'}</td>
                      <td>{row.listed_date ?? '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <button type="button" className="btn-download-pdf" onClick={handleDownloadPdf}>
              Download PDF
            </button>
          </>
        ) : (
          <p className="no-generated-data">Run &quot;Process Data&quot; to generate and view data here.</p>
        )}
      </section>

      <footer className="dashboard-footer">
        <p>End-to-End Backend Verification: COMPLETE</p>
      </footer>
    </div>
  );
}
