import os

class ReportGenerator:
    """
    Enhanced Reporting Layer: Generates deep-dive dashboard for the 7 quality dimensions.
    """
    def __init__(self):
        self.base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    def generate_summary(self, report):
        if not report:
            print("[!] Error: No report data to display.")
            return

        if report.get('status') == "No Data Found for this period":
            print("\n" + "!"*80)
            print("  [!] NO DATA FOUND FOR THIS DATE RANGE")
            print("  Please check your filter dates and try again.")
            print("!"*80 + "\n")
            return

        print("\n" + "╔" + "═"*78 + "╗")
        print("║" + " "*28 + "📍 MASTER QUALITY DASHBOARD" + " "*24 + "║")
        print("╠" + "═"*78 + "╣")
        print(f"║  OVERALL TRUSTABILITY SCORE: {report['overall_trustability']:>6}%" + " "*41 + "║")
        print("╠" + "─"*78 + "╢")
        
        for dim, score in report['dimensions'].items():
            bar = "█" * int(score / 10) + "░" * (10 - int(score / 10))
            print(f"║  {dim:<15} [{bar}] {score:>6}%" + " "*42 + "║")
            
        print("╚" + "═"*78 + "╝\n")

    def save_report(self, report, filename="final_quality_report.txt"):
        if not report:
            return None
        report_path = os.path.join(self.base_dir, "data", "processed", filename)
        
        explanation = (
            "This report provides a comprehensive analysis of the real estate dataset using the "
            "7 Dimensions of Trustability. Our framework evaluates records for Completeness (missing data), "
            "Accuracy (value realism), Validity (format compliance), Consistency (logical coherence), "
            "Uniqueness (duplicate reduction), Integrity (schema adherence), and Lineage (data origin). "
            "A high Trustability Score ensures that the data is reliable for AI-driven insights."
        )

        with open(report_path, "w", encoding="utf-8") as f:
            f.write("╔" + "═"*78 + "╗\n")
            f.write("║" + " "*28 + "DATA TRUSTABILITY REPORT" + " "*26 + "║\n")
            f.write("╚" + "═"*78 + "╝\n\n")
            
            f.write("--- EXECUTIVE SUMMARY ---\n")
            if report.get('status') == "No Data Found for this period":
                f.write("[!] NO DATA FOUND: No records were fetched or remained after remediation.\n")
                f.write("Please adjust the date filters in main.py.\n\n")
                return report_path
            
            f.write(explanation + "\n\n")
            
            f.write(f"Total Records Processed: {report['total_records']}\n")
            f.write(f"Overall Trustability:    {report['overall_trustability']}%\n\n")
            
            f.write("--- DIMENSION BREAKDOWN & REASONING ---\n")
            for dim, score in report['dimensions'].items():
                if score >= 90:
                    status = "PASS"
                    reason = "High reliability; minimal to no data anomalies detected."
                elif score >= 70:
                    status = "WARN"
                    reason = "Acceptable but contains non-critical gaps or inconsistencies."
                else:
                    status = "FAIL"
                    reason = "Critical level of errors; data requires significant remediation."
                
                f.write(f"📍 {dim:<15}: {score:>6}% [{status}]\n")
                f.write(f"   Reasoning: {reason}\n\n")
            
            f.write("="*80 + "\n")
            f.write("Report generated by the Gesix Data Quality Framework.\n")
            
        print(f"[+] Detailed Technical Report saved: data/processed/{filename}")
        return report_path

    def save_html_report(self, report, filename="dashboard.html"):
        """
        Generates a semantic HTML skeleton for frontend developers.
        Injects the 7 dimensions and their reasoning into a structured layout.
        """
        if not report:
            return None
        report_path = os.path.join(self.base_dir, "data", "processed", filename)
        
        # HTML Template with minimal styling (for developer context)
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gesix Data Trustability Dashboard</title>
    <style>
        body {{ font-family: sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
        header {{ border-bottom: 2px solid #2c3e50; padding-bottom: 10px; margin-bottom: 30px; }}
        .score-box {{ background: #f8f9fa; border-left: 5px solid #2c3e50; padding: 20px; margin-bottom: 20px; }}
        .dimensions-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; }}
        .dim-card {{ border: 1px solid #ddd; padding: 15px; border-radius: 8px; }}
        .status-PASS {{ color: #27ae60; font-weight: bold; }}
        .status-WARN {{ color: #f39c12; font-weight: bold; }}
        .status-FAIL {{ color: #e74c3c; font-weight: bold; }}
    </style>
</head>
<body>
    <header>
        <h1>📊 Data Trustability Dashboard</h1>
        <p>Generated by Gesix Data Quality Framework</p>
    </header>

    <section class="score-box">
"""
        if report.get('status') == "No Data Found for this period":
            html_content += f"""
        <h2 style="color: #e74c3c;">[!] NO DATA FOUND</h2>
        <p>The pipeline successfully executed but found 0 records for the selected date range.</p>
        <p><strong>Action Required:</strong> Please check your start/end dates and run the pipeline again.</p>
    </section>
"""
        else:
            html_content += f"""
        <h2>Overall Trustability: <span id="overall-score">{report['overall_trustability']}%</span></h2>
        <p>Total Records Processed: <span id="total-count">{report['total_records']}</span></p>
    </section>

    <section class="dimensions-grid">
"""
            for dim, score in report['dimensions'].items():
                if score >= 90: status = "PASS"
                elif score >= 70: status = "WARN"
                else: status = "FAIL"
                
                # Simple placeholder reasoning based on scores
                reasoning = "High reliability." if status == "PASS" else "Needs attention." if status == "WARN" else "Critical issues found."
                
                html_content += f"""
        <div class="dim-card" id="dim-{dim.lower()}">
            <h3>{dim}</h3>
            <p>Score: <strong>{score}%</strong></p>
            <p>Status: <span class="status-{status}">{status}</span></p>
            <p><small>{reasoning}</small></p>
        </div>
"""

        html_content += """
    </section>

    <footer style="margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; font-size: 0.8em; color: #777;">
        <p>End-to-End Backend Verification: COMPLETE</p>
    </footer>
</body>
</html>
"""

        with open(report_path, "w", encoding="utf-8") as f:
            f.write(html_content)
            
        print(f"[+] HTML Dashboard Skeleton generated: data/processed/{filename}")
        return report_path
