import os

class ReportGenerator:
    """
    Enhanced Reporting Layer: Generates deep-dive dashboard for the 7 quality dimensions.
    """
    def __init__(self):
        self.base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    def generate_summary(self, report):
        if not report:
            print("[!] Error: No report data to display.")
            return

        print("\n" + "╔" + "═"*50 + "╗")
        print("║" + " "*12 + "📍 MASTER QUALITY DASHBOARD" + " "*11 + "║")
        print("╠" + "═"*50 + "╣")
        print(f"║  OVERALL TRUSTABILITY SCORE: {report['overall_trustability']:>6}%" + " "*13 + "║")
        print("╠" + "─"*50 + "╢")
        
        for dim, score in report['dimensions'].items():
            bar = "█" * int(score / 10) + "░" * (10 - int(score / 10))
            print(f"║  {dim:<15} [{bar}] {score:>6}%" + " "*14 + "║")
            
        print("╚" + "═"*50 + "╝\n")

    def save_report(self, report, filename="final_quality_report.txt"):
        report_path = os.path.join(self.base_dir, "data", "processed", filename)
        
        explanation = (
            "This report provides a comprehensive analysis of the real estate dataset using the "
            "7 Dimensions of Trustability. Our framework evaluates records for Completeness (missing data), "
            "Accuracy (value realism), Validity (format compliance), Consistency (logical coherence), "
            "Uniqueness (duplicate reduction), Integrity (schema adherence), and Lineage (data origin). "
            "A high Trustability Score ensures that the data is reliable for AI-driven insights and "
            "automated decision-making, while lower scores indicate that further manual review or "
            "data remediation is required to maintain system integrity."
        )

        with open(report_path, "w", encoding="utf-8") as f:
            f.write("╔" + "═"*68 + "╗\n")
            f.write("║" + " "*23 + "DATA TRUSTABILITY REPORT" + " "*21 + "║\n")
            f.write("╚" + "═"*68 + "╝\n\n")
            
            f.write("--- EXECUTIVE SUMMARY ---\n")
            f.write(explanation + "\n\n")
            
            f.write(f"Total Records Processed: {report['total_records']}\n")
            f.write(f"Overall Trustability:    {report['overall_trustability']}%\n\n")
            
            f.write("--- DIMENSION BREAKDOWN ---\n")
            for dim, score in report['dimensions'].items():
                status = "PASS" if score >= 90 else "WARN" if score >= 70 else "FAIL"
                f.write(f"  {dim:<15}: {score:>6}% [{status}]\n")
            
            f.write("\n" + "="*70 + "\n")
            f.write("Report generated by the Gesix Data Quality Framework.\n")
            
        print(f"[+] Detailed Technical Report saved: data/processed/{filename}")
